version: '3'
services: 
 app:
  build:
   context: ./frontend
  ports: 
   - "3000:80"
   - "3001:443"
  networks:
   - client
 
 jenkins:
  image: jenkins/jenkins
  volumes:
   - "./frontend/jenkins_home:/var/jenkins_home"
  networks:
   - client

networks:
 client:
